### ISSUE TITLE
electron-installer-debian not building the .deb installer

### ISSUE THREAD

**Issue by JesuisOriginal** [electron-userland/electron-installer-debian#198]
**What version of `electron-installer-debian` are you using?**
1.2.0
**What version of `node` and `npm` are you using?**
node 12.0.0
npm 6.9.0
**What operating system are you using?**
Pop!OS 18 , based on Ubuntu 18
**Can you compile the [example app](https://github.com/electron-userland/electron-installer-debian/tree/master/example) successfully?**
yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/electron-userland/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
`$ electron-installer-debian --src dist/app-linux-x64/ --dest dist/installers/ --arch amd64`
**What did you expect to happen?**
Build a .deb installer by running the `$ electron-installer-debian --src dist/app-linux-x64/ --dest dist/installers/ --arch amd64` command after building.
```json
{
  "name": "ZeroToHero",
  "productName": "JSClass",
  "version": "2.0.0",
  "description": "Uma Aula de JavaScript para Designers.",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-packager .",
    "build64": "electron-packager . JSClass --platform linux --arch x64 --out dist/",
    "deb64": "electron-installer-debian --src dist/JSClass-linux-x64/ --dest dist/installers/ --arch amd64",
    "package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds",
    "package-win": "electron-packager . app --overwrite --asar=true --platform=win32 --arch=ia32 --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Electron Tutorial App\"",    
    "package-linux": "electron-packager . app --overwrite --asar=true --platform=linux --arch=x64  --prune=true --out=release-builds"
  },
  "repository": "#",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "https://github.com/users/JesuisOriginal",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^5.0.0",
    "electron-installer-debian": "^0.6.0",
    "electron-packager": "^9.0.0"
  }
}
```
**What actually happened?**
```bash
Error: Error creating contents of package: Error creating binary symlink: could not find the Electron app binary at "dist/app-linux-x64/ZeroToHero". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at /usr/local/lib/node_modules/electron-installer-debian/node_modules/electron-installer-common/src/installer.js:146:17
    at async Promise.all (index 3) Error: Error creating contents of package: Error creating binary symlink: could not find the Electron app binary at "dist/app-linux-x64/ZeroToHero". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at /usr/local/lib/node_modules/electron-installer-debian/node_modules/electron-installer-common/src/installer.js:146:17
    at async Promise.all (index 3)
```

**Comment by malept** [comment]
1. You're using very outdated versions of Electron Packager and `electron-installer-debian` in your `package.json` file.
2. It tells you in the error message what the solution is:
```
You may need to re-bundle the app using Electron Packager's "executableName" option.
```

**Comment by raphael10-collab** [comment]
I suddenly got the same error. 

And solved adding to the `packagerConfig` in `package.json` : 

      "packagerConfig": {
          "executableName": "playground"
      },

Why does this kind of error happen?
